language: go
services:
  - docker
go:
  - '1.16'
install:
  - make tools
jobs:
  include:
    - stage: run tests and build
      script: make test build
    - stage: check if commands in readme still work
      script: make test-readme
      if: type != pull_request # test-readme currently always clones master so it might fail on pull-requests that change the README
