language: go
go:
  - '1.16'
install:
  - make tools
jobs:
  include:
    - stage: run tests and build
      script: make test build
    - stage: run web build and e2e test
      script: make web-build web-e2e
      before_install: nvm install 15.11.0 && nvm use 15.11.0
      addons:
        chrome: stable
    - stage: check if commands in readme still work
      script: make test-readme
      services:
        - docker
      if: type != pull_request # test-readme currently always clones master so it might fail on pull-requests that change the README